version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.17

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      
  deploy:
    machine:
      enabled: true

    working_directory: ~/client

    steps:
      - add_ssh_keys:
          fingerprints:
            - "ad:d3:fc:6f:b6:e9:5c:ab:ea:92:4e:5c:71:83:6b:37"
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/shadeemerhi/scheduler.git master:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build